name: kumeong_store
description: KU-멍가게 Flutter 앱 (StatefulShellRoute 기반 탭 라우팅)
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^16.1.0

  # UI/UX & Utils
  intl: ^0.19.0
  timeago: ^3.6.0
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.6

  # Maps / Device / Media / Intent
  flutter_naver_map: ^1.3.0
  geolocator: ^9.0.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
